apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 82
    volumeMounts:
    - name: nginx-config-vol
      mountPath: /etc/nginx/conf.d
    - name: html-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-config-vol
    configMap:
      name: nginx-config
  - name: html-vol
    persistentVolumeClaim:
      claimName: nginx-pvc
